#!/usr/bin/env php
<?php

// Check
if(php_sapi_name() !== 'cli') {
	echo 'Slab CLI can only be accessed from command line.';
	die(-1);
}


// Define
define('SLAB_CLI_BOOT', true);
define('WP_USE_THEMES', false);


// Setup
require_once '../../../wp-load.php';
@ini_set('memory_limit', -1);


// Collect
$commands = slab('Slab\Cli\CommandCollection');
do_action('slab_commands', $commands);


// Execute
$status = slab('Slab\Cli\Dispatcher')->dispatch($argv);
die($status);
